### ISSUE TITLE
Inconsistent Behavior for NaN Entries, Euclid vs Pearson

### ISSUE THREAD

**Issue by JaKasb** [zpzim/SCAMP#12]
Thanks for the SCAMP Implementation. I am using it for my current research project.

If the input timeseries contains NaN entries and output_pearson=**false**, SCAMP returns **NaN**  at the position of the input NaN.
If the timeseries contains NaN entries and output_pearson=**true** SCAMP returns **-2.0** at the position of the input NaN.

I understand that you can't initialize the distance-matrix with NaN because:
```
NaN < 1 = False
NaN > 1 = False
```
Consequently the running min() update would fail for NaN initialisation.

https://github.com/zpzim/SCAMP/commit/369a16539b1a9f68908dc6659be44e28d8def0c1

Do you think it would make sense to write a post-process function to replace the -2.0 values by NaN values for output_pearson=true ?
Or do you think it would be better keep the code and just mention the -2.0 output in the documentation for the output_pearson flag ?

**Comment by zpzim** [comment]
Yea, this is reasonable. I'll look at it when I get a chance.

Thanks for opening the issue!
