### ISSUE TITLE
SCAMP Formulas

### ISSUE THREAD

**Issue by damianidis** [zpzim/SCAMP#39]
Can you provide the derivations for these two SCAMP equations?

![image](https://user-images.githubusercontent.com/67708746/86281557-bd6c1400-bbab-11ea-9c70-00e14862ba4a.png)

Based on [wikipedia](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Online), the upper equation looks wrong. Shouldn't the covariance (`cv(i, j, m-1)`) be multiplied by `m-1` and then the entire right side of the equation should be divided by `m`. What do you think?

In the bottom equation for `cv(i-1, j-1, m)`, can you show how that equation is derived? I can write it with respect to `cv(i-1, j-1, m-1)` but don't see how it can be manipulated with respect to ``cv(i, j, m-1)`.

**Comment by zpzim** [comment]
@kavj  Can you take a stab at this? You wrote that derivation. 

Reference [1] has more of the theory behind this as well.

[1] https://prod-ng.sandia.gov/techlib-noauth/access-control.cgi/2008/086212.pdf

**Comment by kavj** [comment]
Each mean here is with respect to m - 1 terms. How did you arrive at that conclusion? If cv holds covariance over m - 1 terms, then multiplying by m - 1 turns it into a centered sum of products without any rescaling. You can see the same formula used on pg 13 of that paper. If you're looking at wikipedia, also see Welford's method.

The bottom equation is what you would get if carrying out summation in reverse order. As you will note, the formula stated in [1] doesn't analyze the order in which terms are summed. It just indicates how to combine mean and covariance over m - 1 terms with an mth term in each sequence to obtain covariance over m terms. 

On a side note, does github support inline LaTeX? It would make this easier.

**Comment by damianidis** [comment]
> Each mean here is with respect to m - 1 terms. How did you arrive at that conclusion? If cv holds covariance over m - 1 terms, then multiplying by m - 1 turns it into a centered sum of products without any rescaling. You can see the same formula used on pg 13 of that paper. If you're looking at wikipedia, also see Welford's method.

I understand that the mean is with respect to `m-1` terms and I understand the relationship between the centered sum of products and covariance. The formula on page 13 only represents the centered sum of products (not covariance). In the Wikipedia link that I provided, I'm actually pointing to Welford's online method which shows that covariance is:

![241549051c7dfd419243943194d0912785b9fbf0](https://user-images.githubusercontent.com/67708746/86300676-9aecf180-bbd1-11ea-980c-8528022007f9.png)

Notice that this is different from your formula which I think is showing the centered sum of products and not the covariance (I'm assuming that `cv` stands for covariance?). Maybe I'm misinterpreting things.

> The bottom equation is what you would get if carrying out summation in reverse order. As you will note, the formula stated in [1] doesn't analyze the order in which terms are summed. It just indicates how to combine mean and covariance over m - 1 terms with an mth term in each sequence to obtain covariance over m terms.

It would be helpful if you could start with this and show how to derive the second equation equation in the above formula:

![img-5bc50344875ed422](https://user-images.githubusercontent.com/67708746/86301338-a3dec280-bbd3-11ea-8a7d-e2ade5ca419e.png)

Thanks in advance!

> On a side note, does github support inline LaTeX? It would make this easier.

Maybe you can write a Github gist and name the file as `.ipynb` and it should render the LaTex. [Here's an example](https://gist.github.com/cyhsutw/d5983d166fb70ff651f027b2aa56ee4e). Hope that helps.

**Comment by kavj** [comment]
Oh right right, I could have been less ambiguous there. I forget my own writing, especially when squinting at a screengrab of it. I probably wrote that initially around 3 years ago. 

You're correct, it's a sum of products there, which is consistent with Zach's implementation. He gets correlation by dividing out each norm.

Let me try that as a gist.

**Comment by damianidis** [comment]
> Oh right right, I could have been less ambiguous there. I forget my own writing, especially when squinting at a screengrab of it. I probably wrote that initially around 3 years ago.

> You're correct, it's a sum of products there, which is consistent with Zach's implementation. He gets correlation by dividing out each norm.

Great! That definitely helps

> Let me try that as a gist.

While you're at this, would you mind showing the steps for this as well?

![Untitled](https://user-images.githubusercontent.com/67708746/86302317-4e57e500-bbd6-11ea-976d-54ecde2ebf83.png)

I'm failing to see where the `1/2` is coming from and then what is represented by the ellipses.

**Comment by kavj** [comment]
I never actually got a gist to render correctly. I'll have to look into that, as I haven't used them much. I **may** still write something more intuitive, but the starting formula does match the one on pg 13 of reference 1, which Zach posted, and  that includes a proof. 

On the second pasted snippet, starting from the equation in [1], I split the first term of cv_i-1,j-1 and the last term of cv_i,j. 
I just didn't explicitly write a step containing cv_i,j,(m-1) - cv_i,j,(m-1).

The elipses ensure the correct terms are multiplied.
The coefficient 1/2 is just twisted factorization.  It's the same as below using different variable names.

(1/2) * (a + c) * (b - d) + (1/2) * (a - c) * (b + d) = (1/2) (a * b - a * d + c * b - c * d + a * b + a * d - c * b - c * d)
 = (1/2) * (2 * a * b - 2 * c * d)
= a * b - c * d

If it didn't contain 1/2, you would have the wrong result.

Twisted factorization was used to limit the number of arrays required to store precomputed values for comparisons across a single time series. It doesn't buy you anything if comparing two distinct time series. 

I no longer suggest the use of twisted factorization for this, because in the case where one equation results in underflow and the other is large, we end with a highly perturbed summation. This showed up in cases where a signal dropped out completely over some time range.

If no perturbation due to carried residual values across windows is permissible, you would use matrix multiplication instead, since that's effectively what you're doing here anyway using a lookahead method with the addition of interleaved reduction steps.

**Comment by damianidis** [comment]
> I no longer suggest the use of twisted factorization for this, because in the case where one equation results in underflow and the other is large, we end with a highly perturbed summation. This showed up in cases where a signal dropped out completely over some time range.
>
> If no perturbation due to carried residual values across windows is permissible, you would use matrix multiplication instead, since that's effectively what you're doing here anyway using a lookahead method with the addition of interleaved reduction steps.

Based on this, does this mean that, in practice, you would omit the twisted factorization (and the df and dg) steps and just leave the equations as:


![img-4d506261592a1f6b](https://user-images.githubusercontent.com/67708746/86360776-dd014c00-bc40-11ea-868f-ced595b415a2.png)
![img-bb04725295c74901](https://user-images.githubusercontent.com/67708746/86360789-e094d300-bc40-11ea-8a22-f74b9cbe32a3.png)


And then substitute `cv` for `QT` starting in equation (6) in your paper?


![Untitled](https://user-images.githubusercontent.com/67708746/86361563-0bcbf200-bc42-11ea-958a-11a7b3fa7f1d.png)

**Comment by kavj** [comment]
The scope of this conversation is beyond what I think is appropriate for an open issue on github, but yes, you are correct. I had other complaints with the preceding formula.

**Comment by zpzim** [comment]
@damianidis I believe your initial question and follow up questions have been answered and I am in agreement with @kavj that this conversation has moved beyond SCAMP. It would be helpful to know the context in which these questions are being asked. If this was being framed as a way to improve the numerical properties of SCAMP that would great, and most appreciated.

It's a strange coincidence that you ask your question now, as Kaveh and I had been talking about applying these equations better in the context of SCAMP very recently. (See Issue #38 )

We are always glad to work with people trying to improve this stuff. But I think if it doesn't pertain to SCAMP we should take this to emails.

**Comment by zpzim** [comment]
Closing this issue as the original question has been resolved. Please feel free to reach out via email if you'd like to discuss further.
